version: "3"

volumes:
    postgres-data:
        driver: local
services:
    web:
        restart: always
        build: .
        ports:
            - "8000:8000"
        links:
            - postgresdb:postgresdb
        volumes:
            - ./:/usr/src/app
        env_file: .env
    postgresdb:
        restart: always
        image: postgres:latest
        env_file: .env
        expose: 
            - "5433"
        ports:
            - "5433:5432"
        volumes: 
            - postgres-data:/var/lib/postgres