web:
    restart: always
    build: .
    ports:
        - "8000:8000"
    links:
        - postgresdb:postgresdb
    volumes:
        - ./:/usr/src/app
    env_file: .env
dbdata:
    image: tianon/true
    volumes: 
        - /var/lib/postgres
postgresdb:
    restart: always
    image: postgres:latest
    env_file: .env
    ports:
        - "5432:5432"
    volumes_from: 
        - dbdata